// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opipazvvefdcdyywybpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9waXBhenZ2ZWZkY2R5eXd5YnBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzU2OTQsImV4cCI6MjA1OTY1MTY5NH0.VlI8VCi4kIPL1inCSH90RsLNZ1j1IZlEuvOlW869L-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);